### ISSUE TITLE
Meta issue for Azure Resource Manager templates

### ISSUE THREAD

**Issue by gunnaraasen** [influxdata/azure-resource-manager-influxdb-enterprise#1]
List of TODO items for the ARM templates:

- [x] Review networking and resource templates are correct. @chobbs  
- [x] Add secondary volumes InfluxDB on data and meta nodes. @chobbs 
- [x] Add in hostnames. @chobbs  
- [x] Add in Azure extension scripts for setup. @chobbs 
- [x] Template testing and infrastructure review. @gunnaraasen  
- [x] Template  & conf scripting  updates and modification. @gunnaraasen/ @chobbs 
- [x] Review high-level architecture. @gunnaraasen
